version: 2
updates:
  # Enable version updates for Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/meet-geno"
    schedule:
      interval: "monthly"

  # Enable version updates for rust
  - package-ecosystem: "cargo"
    directory: "/meet-geno/src-tauri"
    schedule:
      interval: "monthly"
