---
default_language_version:
    python: python3.10
default_stages: [commit, push]
files: gero/w*
exclude: gero/docs/w*
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: check-yaml
          - id: check-toml
          - id: debug-statements
          - id: end-of-file-fixer
          - id: check-added-large-files
          - id: check-ast
          - id: check-json
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: forbid-new-submodules

    - repo: https://github.com/pre-commit/mirrors-autopep8
      rev: 'v1.6.0'
      hooks:
          - id: autopep8

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v0.950' 
      hooks:
          - id: mypy
          # args: [--no-strict-optional, --ignore-missing-imports]

    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.21.0    # or higher tag
      hooks:
          - id: yamllint
            args: [--format, parsable, --strict]

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.1    # or other specific tag
      hooks:
          - id: yamlfmt

    # - repo: https://github.com/Lucas-C/pre-commit-hooks-markup
    #   rev: v1.0.1
    #   hooks:
    #       - id: rst-linter

    - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
      rev: v8.0.0
      hooks:
          - id: commitlint
            stages: [commit-msg]
            additional_dependencies: ['@commitlint/config-conventional']

    # - repo: https://github.com/PyCQA/pydocstyle
    #   rev: 6.1.1
    #   hooks:
    #       - id: pydocstyle

    # - repo: https://github.com/miki725/importanize/
    #   rev: '0.7' 
    #   hooks:
    #       - id: importanize
    #         args: [--verbose]

    - repo: https://github.com/sirosen/texthooks
      rev: 0.3.0
      hooks:
          - id: fix-smartquotes
            # replace default single quote chars with this set:
            # apostrophe, fullwidth apostrophe, left single quote, single high
            # reversed-9 quote, right single quote
            args: [--single-quote-codepoints, '0027,FF07,2018,201B,2019']
          - id: fix-ligatures

    - repo: https://github.com/sondrelg/pep585-upgrade
      rev: 'v1.0.1'
      hooks:
          - id: upgrade-type-hints

    # - repo: https://github.com/psf/black
    #   rev: 22.3.0
    #   hooks:
    #       - id: black
    #         language_version: python3

    - repo: https://github.com/mwouts/jupytext
      rev: v1.13.7  # CURRENT_TAG/COMMIT_HASH
      hooks:
          - id: jupytext
            args: [--sync]
    
    # - repo: https://github.com/leoll2/copyright_notice_precommit
    #   rev: 0.1.1
    #   hooks:
    #       - id: copyright-notice
    #         args: [--notice=copyright.txt]