TipRM:
  name: Tip Resource Manager
  type: Resorce Manager
  address: modules/tip_rm
  description: Tip RM manages tip boxes with various tip sizes in them

Gantry:
  name: Gantry Instrument
  type: Instrument
  address: modules/instrument
  description: Gantry instrument allows motion in XZ axis

