title: PCR
description: ...

version: 0.0.1

data:
  - name: annealing_temp
    description: ...
    type: float
  - name: annealing_duration
    description: ...
    type: float

workflow:
  - attempt_pickup_tip

