[workspace]

members = [
    "slider-common",

    "gantry-controller",
    "centrifuge-controller",

    "reagent-rm",
    "sample-rm",
    "tool-rm",
    "tip-rm",
    "cartridge-rm"
]

exclude = [
    "slider-uc"
]
