# Installs Node.js dependencies and pnpm, and checks formatting + linting

name: Lint Node.js

on:
  push:
    branches:
      - master
    paths:
      - "meet-geno"
  # pull_request:
  #   paths:
  #     - "meet-geno"
  #   paths-ignore:
  #     - "meet-geno/src-tauri/**"

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Set up pnpm package manager
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set up Node.js LTS v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install dependencies from lockfile
        run: pnpm install --frozen-lockfile

      - name: Run lint step
        run: pnpm lint
