name: Test slider-common
on:
  push:
    paths:
      - 'firmware/slider-common/**'
  pull_request:
    paths:
      - 'firmware/slider-common/**'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cd firmware/slider-common && cargo test --verbose
